assert(SMODS.load_file("objects/ringleader_type.lua"))()
assert(SMODS.load_file("functions/misc_functions.lua"))()
assert(SMODS.load_file("functions/ui_functions.lua"))()
assert(SMODS.load_file("functions/button_callbacks.lua"))()
assert(SMODS.load_file("ringleaders/the_tester.lua"))()